version: '3.8'
services:
  travel-mongo:
    container_name: travel-mongo
    image: 180140_travel-mongo
    volumes:
      - ./travelDB-mongoDB/travel-offers:/var/my-db
      - ./travelDB-mongoDB/init-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./travelDB-mongoDB/init-scripts/custom-entrypoint.sh:/custom-entrypoint.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=TravelDB
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
      
  gateway-api:
    container_name: gateway-api
    image: 180140_gateway-api
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
      - redis-service
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  frontend-api:
    container_name: frontend-api
    image: 180140_frontend-api
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  rabbitmq-gateway:
    container_name: rabbitmq-gateway
    image: 180140_rabbitmq-gateway
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    
  api-gateway:
    container_name: api-gateway
    image: 180140_api-gateway
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s
    
  payment-service:
    container_name: payment-service
    image: 180140_payment-service
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    environment:
      - FLASK_APP=app.py
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  activities-service:
    container_name: activities-service
    image: 180140_activities-service
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    environment:
      - FLASK_APP=app.py
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  reservation-service:
    container_name: reservation-service
    image: 180140_reservation-service
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    environment:
      - FLASK_APP=app.py
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  postgres-db-reservations:
    container_name: postgres-db-reservations
    image: 180140_postgres-db-reservations
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  toc-postgres:
    container_name: toc-postgres
    image: 180140_toc-postgres
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  toc-service:
    container_name: toc-service
    image: 180140_toc-service
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

  redis-service:
    container_name: redis-service
    image: 180140_redis-service
    ports:
      - "6379:6379"
    networks:
      - 180140_backend-network
    deploy:
      replicas: 1
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 0
        window: 120s

networks:
  180140_backend-network:
    name: 180140_backend-network
    driver: overlay
