version: '3.8'
services:
  travel-mongo:
    container_name: travel-mongo
    #build: . #
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./travelDB-mongoDB/travel-offers:/var/my-db
      - ./travelDB-mongoDB/init-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./travelDB-mongoDB/init-scripts/custom-entrypoint.sh:/custom-entrypoint.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=TravelDB
    networks:
      - backend-network
  gateway_api:
    container_name: gateway-api
    build: ./gateway_api
    ports:
      - "5000:5000"
    depends_on:
      - travel-mongo
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - backend-network
    

networks:
  backend-network:
    name: backend-network
    driver: bridge
