version: '3.8'
services:
  travel-mongo:
    container_name: travel-mongo
    image: mongo-rsww480
    volumes:
      - ./travelDB-mongoDB/travel-offers:/var/my-db
      - ./travelDB-mongoDB/init-scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./travelDB-mongoDB/init-scripts/custom-entrypoint.sh:/custom-entrypoint.sh
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadmin
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=TravelDB
    networks:
      - backend-network
      
  gateway_api:
    container_name: gateway-api
    image: gateway-api-rsww480
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
      - redis
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - backend-network

  frontend:
    container_name: frontend-api
    image: frontend-api-rsww480
    ports:
      - "8080:8080"
    environment:
      - FLASK_APP=app/app.py
      - FLASK_RUN_HOST=0.0.0.0
    networks:
      - backend-network

  rabbitmq-gateway:
    container_name: rabbitmq-gateway
    image: rabbitmq-gateway-rsww480
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend-network
    
  api-gateway:
    container_name: api-gateway
    image: api-gateway-rsww480
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    networks:
      - backend-network
    
  payment_service:
    container_name: payment-service
    image: payment-service-rsww480
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    environment:
      - FLASK_APP=app.py
    networks:
      - backend-network

  activities_service:
    container_name: activities-service
    image: activities-service-rsww480
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    environment:
      - FLASK_APP=app.py
    networks:
      - backend-network

  reservation_service:
    container_name: reservation_service
    image: reservation-service-rsww480
    depends_on:
      - travel-mongo
      - rabbitmq-gateway
    environment:
      - FLASK_APP=app.py
    networks:
      - backend-network

  postgres_db:
    container_name: postgres-db-reservations
    image: postgres-db-reservations-rsww480
    networks:
      - backend-network

  redis:
    container_name: redis-service
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend-network

networks:
  backend-network:
    name: backend-network
    driver: bridge
